# Networks for communication between services
networks:
  web:
    driver: bridge

# Volumes for data, config, and logs
volumes:
  config:
  data:
  log:

services:
  # Flask server
  flask_gunicorn_web:
    container_name: flask_gunicorn_web
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - web

  # Nginx reverse proxy
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - flask_gunicorn_web
    ports:
      - "80:80"    # HTTP traffic
      - "443:443"  # HTTPS traffic (if needed later)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - web
